server:
    port: 8080

camunda:
    bpm:
        admin-user:
            id: kermit
            password: superSecret
            firstName: Kermit
        filter:
            create: All tasks
        database:
            type: postgres

spring:
    datasource: 
        url: jdbc:postgresql://127.0.0.1:5432/camunda
        username: camunda
        password: camunda12345
        driver-class-name: org.postgresql.Driver